"""Multi-Agent Consensus Engine — LocLM V8.

Provides multi-agent proposal gathering, agreement scoring, conflict resolution,
and unified consensus plan synthesis for high-ambiguity or high-impact tasks.
"""

from __future__ import annotations

import enum
import logging
from typing import Any

from pydantic import BaseModel, Field

from loclm.agents.base import AgentRole
from loclm.models.base import ChatMessage
from loclm.models.manager import ModelManager

logger = logging.getLogger(__name__)


class ConsensusStatus(str, enum.Enum):
    """Overall state of multi-agent agreement."""

    AGREEMENT = "agreement"  # High agreement score (>= 0.75)
    MAJORITY = "majority"    # Moderate agreement score (0.50 - 0.74)
    CONFLICT = "conflict"    # Low agreement score (< 0.50)


class AgentProposal(BaseModel):
    """Structured proposal generated by an agent role during consensus deliberation."""

    agent_role: AgentRole = Field(description="Role proposing this solution")
    proposal_title: str = Field(description="Brief title of the proposed approach")
    solution_summary: str = Field(description="Detailed summary of the proposed solution")
    confidence_score: float = Field(
        default=0.8,
        description="Confidence score between 0.0 and 1.0",
    )
    reasoning: str = Field(default="", description="Rationale behind this approach")
    potential_risks: list[str] = Field(default_factory=list, description="Identified risks or downsides")


class ConsensusResult(BaseModel):
    """Final consensus evaluation result synthesizing proposals from multiple agents."""

    task: str = Field(description="Original user request")
    consensus_status: ConsensusStatus = Field(description="Agreement status")
    agreement_score: float = Field(
        description="Calculated agreement score between 0.0 and 1.0",
    )
    winning_proposal: AgentProposal = Field(description="Selected highest-scoring proposal")
    synthesized_plan: str = Field(description="Unified execution plan combining proposal strengths")
    proposals: list[AgentProposal] = Field(default_factory=list)
    dissenting_opinions: list[str] = Field(default_factory=list)


class ConsensusManager:
    """Manages multi-agent proposal generation, consensus scoring, and plan synthesis."""

    def __init__(self, model_manager: ModelManager) -> None:
        self.model_manager = model_manager

    async def run_consensus(
        self,
        task: str,
        roles: list[AgentRole] | None = None,
    ) -> ConsensusResult:
        """Run multi-agent deliberation to reach consensus on a task.

        Args:
            task: The user task or question.
            roles: List of participating AgentRoles. Default: CODING, KNOWLEDGE, TERMINAL.

        Returns:
            ConsensusResult with proposals, agreement score, and synthesized plan.
        """
        if not roles:
            roles = [AgentRole.CODING, AgentRole.KNOWLEDGE, AgentRole.TERMINAL]

        logger.info("ConsensusManager: initiating deliberation for task across roles %s", [r.value for r in roles])

        # Step 1: Gather proposals from each role
        proposals: list[AgentProposal] = []
        for role in roles:
            proposal = await self._generate_proposal(task, role)
            proposals.append(proposal)

        # Step 2: Compute agreement score and status
        agreement_score, status = self._evaluate_consensus_score(proposals)

        # Step 3: Select winning proposal (highest confidence)
        winning_proposal = max(proposals, key=lambda p: p.confidence_score)

        # Step 4: Extract dissenting opinions
        dissenting = [
            f"[{p.agent_role.value}] Raised risk: {', '.join(p.potential_risks)}"
            for p in proposals
            if p.potential_risks and p.agent_role != winning_proposal.agent_role
        ]

        # Step 5: Synthesize unified consensus plan
        synthesized = await self._synthesize_plan(task, proposals, winning_proposal)

        return ConsensusResult(
            task=task,
            consensus_status=status,
            agreement_score=agreement_score,
            winning_proposal=winning_proposal,
            synthesized_plan=synthesized,
            proposals=proposals,
            dissenting_opinions=dissenting,
        )

    async def _generate_proposal(self, task: str, role: AgentRole) -> AgentProposal:
        """Prompt the LLM to generate a structured proposal from the perspective of a specific role."""
        messages = [
            ChatMessage(
                role="system",
                content=f"You are a specialized {role.value} agent focused on offline precision.",
            ),
            ChatMessage(
                role="user",
                content=(
                    f"You are acting as the {role.value.upper()} AGENT in a multi-agent AI system.\n"
                    f"Task: {task}\n\n"
                    f"Propose your best approach from the perspective of {role.value}.\n"
                    f"Return a clean proposal with Approach Title, Detailed Solution Summary, Reasoning, and Potential Risks."
                ),
            ),
        ]
        try:
            text = await self.model_manager.chat(messages=messages, temperature=0.3)
            text = text.strip()
            return AgentProposal(
                agent_role=role,
                proposal_title=f"{role.value.title()} Solution Approach",
                solution_summary=text,
                confidence_score=0.85,
                reasoning=f"Proposed using {role.value} domain specialization",
                potential_risks=[f"Limited to {role.value} scope"],
            )
        except Exception as exc:
            logger.warning("Failed to generate proposal for role %s: %s", role.value, exc)
            return AgentProposal(
                agent_role=role,
                proposal_title=f"Fallback {role.value} Proposal",
                solution_summary=f"Standard execution plan for {task}",
                confidence_score=0.6,
                reasoning="Fallback proposal due to generation error",
                potential_risks=["Fallback plan"],
            )

    @staticmethod
    def _evaluate_consensus_score(proposals: list[AgentProposal]) -> tuple[float, ConsensusStatus]:
        """Compute an overall agreement score (0.0 - 1.0) among agent proposals."""
        if not proposals:
            return 0.0, ConsensusStatus.CONFLICT
        if len(proposals) == 1:
            return 1.0, ConsensusStatus.AGREEMENT

        # Calculate average confidence
        avg_conf = sum(p.confidence_score for p in proposals) / len(proposals)

        # Check keyword overlaps in solution summaries as a proxy for structural similarity
        words_sets = [set(p.solution_summary.lower().split()) for p in proposals]
        intersection = set.intersection(*words_sets) if words_sets else set()
        union = set.union(*words_sets) if words_sets else set()
        jaccard = len(intersection) / max(len(union), 1)

        # Weighted combination
        score = round(0.6 * avg_conf + 0.4 * min(jaccard * 3.0, 1.0), 2)
        score = min(max(score, 0.0), 1.0)

        if score >= 0.75:
            status = ConsensusStatus.AGREEMENT
        elif score >= 0.50:
            status = ConsensusStatus.MAJORITY
        else:
            status = ConsensusStatus.CONFLICT

        return score, status

    async def _synthesize_plan(
        self,
        task: str,
        proposals: list[AgentProposal],
        winning_proposal: AgentProposal,
    ) -> str:
        """Combine proposals into a unified execution plan."""
        parts = [
            f"=== CONSENSUS EXECUTION PLAN ===",
            f"Primary Strategy ({winning_proposal.agent_role.value}): {winning_proposal.proposal_title}",
            f"\nCore Solution:\n{winning_proposal.solution_summary}",
        ]

        # Add contributing perspectives
        contributors = [p for p in proposals if p.agent_role != winning_proposal.agent_role]
        if contributors:
            parts.append("\n=== CONTRIBUTING AGENT PERSPECTIVES ===")
            for c in contributors:
                parts.append(f"• [{c.agent_role.value}]: {c.proposal_title} - {c.solution_summary[:150]}...")

        return "\n\n".join(parts)
